sensor:
  # Living room temperature
  - platform: mqtt
    name: Living Room Temp
    unit_of_measurement: "°C"
    state_topic: "home/temperature/living_room"

binary_sensor:
  - platform: mqtt
    name: "Living Room Window Switch"
    state_topic: "shellies/shellyswitch-1351AD/input/1"
    payload_on: "1"
    payload_off: "0"

light:
  - platform: mqtt
    name: "TV LEDS"
    state_topic: "living_room/rgbtvleds/switch/status"
    command_topic: "living_room/rgbtvleds/switch/set"
    rgb_state_topic: "living_room/rgbtvleds/color/status"
    rgb_command_topic: "living_room/rgbtvleds/color/set"
    qos: 0
    retain: false
    on_command_type: first
    payload_on: "True"
    payload_off: "False"
    optimistic: false

  - platform: mqtt
    name: "Living Room RGB"
    state_topic: "living_room/awox1/switch/status"
    command_topic: "living_room/awox1/switch/set"
    brightness_state_topic: "living_room/awox1/brightness/status"
    brightness_command_topic: "living_room/awox1/brightness/set"
    color_temp_state_topic: "living_room/awox1/temperature/status"
    color_temp_command_topic: "living_room/awox1/temperature/set"
    rgb_state_topic: "living_room/awox1/color/status"
    rgb_command_topic: "living_room/awox1/color/set"
    brightness_scale: 100
    qos: 0
    retain: false
    on_command_type: brightness
    payload_on: "True"
    payload_off: "False"
    optimistic: false

  - platform: mqtt
    name: "Living Room Table"
    state_topic: "shellies/shellyswitch-1351AD/relay/0"
    command_topic: "shellies/shellyswitch-1351AD/relay/0/command"
    #availability_topic: "living_room/lights/shelly2/online"
    qos: 0
    retain: false
    payload_on: "on"
    payload_off: "off"
    optimistic: false

  - platform: mqtt
    name: "Living Room Window"
    state_topic: "shellies/shellyswitch-1351AD/relay/1"
    command_topic: "shellies/shellyswitch-1351AD/relay/1/command"
    #availability_topic: "living_room/lights/shelly2/online"
    qos: 0
    retain: true
    payload_on: "on"
    payload_off: "off"
    optimistic: false

  #- platform: group
    #name: Living Room Lights
    #entities:
      #- light.tv_leds
      #- light.living_room_table
      #- light.living_room_window
      #- light.living_room_rgb

switch:
  - platform: flux
    name: Flux Sala
    lights:
      - light.living_room_rgb
    start_time: '7:00'
    stop_time: '01:00'
    start_colortemp: 5000
    sunset_colortemp: 3500
    stop_colortemp: 1900
    disable_brightness_adjust: true
    transition: 30
    interval: 60

counter:
  living_room_window_switch_toggle_count:
    initial: 0
    step: 1

automation old:
  - alias: "Living Room Window Switch Toggle Count"
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.living_room_window_switch
    action:
    - service: counter.increment
      entity_id: counter.living_room_window_switch_toggle_count

  - alias: "Living Room Window Switch Action"
    hide_entity: true
    trigger:
      platform: numeric_state
      entity_id: counter.living_room_window_switch_toggle_count
      above: 0
      for:
        seconds: 1
    #condition:
      #condition: numeric_state
      #entity_id: counter.living_room_window_switch_toggle_count
      #above: 0
    action:
    - service: light.toggle
      data_template:
        entity_id: >
          {% if is_state(trigger.entity_id, '1') %}
            light.living_room_window
          {% else %}
            light.living_room_rgb
          {% endif %}
    - service: counter.reset
      entity_id: counter.living_room_window_switch_toggle_count
