scene:
  - name: Livingroom normal
    entities:
      light.tv_leds:
        state: on
        transition: 2
        brightness_pct: 100

  - name: Livingroom dim
    entities:
      light.tv_leds:
        state: on
        transition: 2
        brightness_pct: 40


media_player:
  # LGTV
  - platform: webostv
    host: !secret living_room_ip
    name: Living Room TV
    timeout: 5
    filename: webostv.conf
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret living_room_tv_mac
    customize:
      sources:
        - MEO
        - Kodi
        - YouTube
        - Netflix

  # Meo box
  - platform: mediaroom
    name: Meo Box
    host: !secret meo_box_ip

  # Kodi
  - platform: kodi
    name: TV Kodi
    host: !secret kodi_ip
    port: 8080
    username: !secret kodi_user
    password: !secret kodi_pass
    enable_websocket: true

  #Universal
  - platform: universal
    name: Media Center
    children:
      - media_player.mediaroom_192_168_1_102
      - media_player.tv_kodi
      - media_player.living_room_tv
    state_template: >
      {% if is_state('media_player.living_room_tv', 'off') %}
        off
      {% else %}
        {% if is_state('sensor.living_room_tv_source', "Kodi") %}
          {{ states('media_player.tv_kodi') }}
        {% elif is_state('sensor.living_room_tv_source', "MEO") %}
          {{ states('media_player.mediaroom_192_168_1_102') }}
        {% elif is_state('sensor.living_room_tv_source', "Netflix") %}
          {{ states('media_player.living_room_tv') }}
        {% else %}
          {{ states('media_player.living_room_tv') }}
        {% endif %}
      {% endif %}
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.living_room_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.living_room_tv
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.living_room_tv
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.living_room_tv
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.living_room_tv
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.living_room_tv
          source: '{{ source }}'
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_tv
          volume_level: '{{ volume_level }}'
    attributes:
      state: media_player.living_room_tv
      is_volume_muted: media_player.living_room_tv|is_volume_muted
      volume_level: media_player.living_room_tv|volume_level
      source: media_player.living_room_tv|source
      source_list: media_player.living_room_tv|source_list


sensor:
  - platform: template
    sensors:
      living_room_tv_source:
        value_template: '{{ states.media_player.living_room_tv.attributes["source"] }}'
        friendly_name: 'Living Room TV Source'

automation old:
  - alias: "When TV is OFF"
    hide_entity: true
    trigger:
    - entity_id: media_player.living_room_tv
      platform: state
      to: 'off'
    - platform: state
      entity_id: sensor.living_room_tv_source
      from: MEO
    action:
    - service: media_player.turn_off
      entity_id: media_player.mediaroom_192_168_1_102
    - service: light.turn_on
      entity_id:  light.tv_leds
    - delay: 00:00:30
    - service: light.turn_off
      entity_id:  light.living_room_table

  - alias: "Turn OFF MEO box based on Living Room TV source"
    hide_entity: true
    trigger:
    - platform: state
      entity_id: sensor.living_room_tv_source
      from: MEO
    action:
    - service: media_player.turn_off
      entity_id: media_player.mediaroom_192_168_1_102


  - alias: "Turn ON MEO box based on Living Room TV source"
    hide_entity: true
    trigger:
    - entity_id: media_player.living_room_tv
      platform: state
      to: 'on'
    - platform: state
      entity_id: sensor.living_room_tv_source
      to: MEO
    condition:
    - condition: state
      entity_id: sensor.living_room_tv_source
      state: MEO
    action:
      service: media_player.turn_on
      entity_id: media_player.mediaroom_192_168_1_102


#- id: led_strip_tv_source_netfilx_aut
  #alias: Led strip based on TV source Netflix
  #trigger:
  #- platform: state
    #entity_id: sensor.living_room_tv_source
    #to: Netflix
  #condition:
  #- condition: state
    #entity_id: sun.sun
    #state: below_horizon
  #- condition: state
    #entity_id: media_player.living_room_tv
    #state: playing
  #- condition: state
    #entity_id: light.tv_leds
    #state: 'on'
  #action:
  #- service: light.turn_on
    #entity_id: light.tv_leds
    #data_template:
      #brightness: 255
      #rgb_color:
      #- '0'
      #- '255'
      #- '0'
#- id: led_strip_tv_source_kodi_aut
  #alias: Led strip based on TV source Kodi
  #trigger:
  #- platform: state
    #entity_id: sensor.living_room_tv_source
    #to: RaspberryPi
  #condition:
  #- condition: state
    #entity_id: sun.sun
    #state: below_horizon
  #- condition: state
    #entity_id: media_player.living_room_tv
    #state: playing
  #- condition: state
    #entity_id: light.tv_leds
    #state: 'on'
  #action:
  #- service: light.turn_on
    #entity_id: light.tv_leds
    #data_template:
      #brightness: 255
      #rgb_color:
      #- '0'
      #- '0'
      #- '255'


#- alias: "Media player paused/stopped"
  #trigger:
    #- platform: state
      #entity_id: media_player.media_center
      #from: 'playing'
      #to: 'idle'
  #condition:
    #- condition: state
      #entity_id: sun.sun
      #state: 'below_horizon'
    #- condition: state
      #entity_id: light.tv_leds
      #state: 'on'
  #action:
      #service: scene.turn_on
      #entity_id: scene.livingroom_normal

#- alias: "Media player playing"
  #trigger:
    #- platform: state
      #entity_id: media_player.media_center
      #to: 'playing'
      #from: 'idle'
  #condition:
    #- condition: state
      #entity_id: sun.sun
      #state: 'below_horizon'
    #- condition: state
      #entity_id: light.tv_leds
      #state: 'on'
  #action:
      #service: scene.turn_on
      #entity_id: scene.livingroom_dim

