- platform: mqtt
  name: "Living Room RGB"
  state_topic: "living_room/awox1/switch/status"
  command_topic: "living_room/awox1/switch/set"
  brightness_state_topic: "living_room/awox1/brightness/status"
  brightness_command_topic: "living_room/awox1/brightness/set"
  color_temp_state_topic: "living_room/awox1/temperature/status"
  color_temp_command_topic: "living_room/awox1/temperature/set"
  rgb_state_topic: "living_room/awox1/color/status"
  rgb_command_topic: "living_room/awox1/color/set"
  brightness_scale: 100
  qos: 0
  retain: false
  on_command_type: brightness
  payload_on: "True"
  payload_off: "False"
  optimistic: false

- platform: mqtt
  name: "Living Room Table"
  state_topic: "shellies/shellyswitch-1351AD/relay/0"
  command_topic: "shellies/shellyswitch-1351AD/relay/0/command"
  #availability_topic: "living_room/lights/shelly2/online"
  qos: 0
  retain: true
  payload_on: "on"
  payload_off: "off"
  optimistic: false

- platform: mqtt
  name: "Living Room Window"
  state_topic: "shellies/shellyswitch-1351AD/relay/1"
  command_topic: "shellies/shellyswitch-1351AD/relay/1/command"
  #availability_topic: "living_room/lights/shelly2/online"
  qos: 0
  retain: true
  payload_on: "on"
  payload_off: "off"
  optimistic: false

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_table
    - light.living_room_window
    - light.living_room_rgb
