- alias: "Presence light get home"
  trigger:
    platform: state
    entity_id: device_tracker.joao_phone
    to: 'home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id:  light.living_room_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.living_room_rgb
      data_template:
        brightness: 180
    - delay: 00:00:30
    - service: light.turn_off
      entity_id: light.living_room_rgb

- alias: "Presence light TV off"
  trigger:
    platform: state
    entity_id: media_player.media_center
    to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id:  light.living_room_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.living_room_rgb
      data_template:
        brightness: 180
    - delay: 00:00:30
    - service: light.turn_off
      entity_id: light.living_room_rgb
