- id: led_strip_tv_source_netfilx_aut
  alias: "Led strip based on TV source Netflix"
  trigger:
  - platform: state
    entity_id: sensor.living_room_tv_source
    to: 'Netflix'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: media_player.living_room_tv
    state: 'playing'
  - condition: state
    entity_id: light.tv_leds
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.tv_leds
    data_template:
      brightness: 255
      rgb_color: ['0','255','0']

- id: led_strip_tv_source_kodi_aut
  alias: "Led strip based on TV source Kodi"
  trigger:
  - platform: state
    entity_id: sensor.living_room_tv_source
    to: 'RaspberryPi'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: media_player.living_room_tv
    state: 'playing'
  - condition: state
    entity_id: light.tv_leds
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.tv_leds
    data_template:
      brightness: 255
      rgb_color: ['0','0','255']

- id: presence_light_get_home
  alias: "Presence light get home"
  trigger:
  - platform: state
    entity_id: device_tracker.joao_phone
    to: 'home'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id:  light.living_room_lights
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.living_room_rgb
    data_template:
      brightness: 180
  - delay: 00:00:30
  - service: light.turn_off
    entity_id: light.living_room_rgb

- id: presence_light_tv_off
  alias: "Presence light TV off"
  trigger:
  - platform: state
    entity_id: media_player.media_center
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id:  light.living_room_lights
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.living_room_rgb
    data_template:
      brightness: 180
  - delay: 00:00:30
  - service: light.turn_off
    entity_id: light.living_room_rgb
