title: J&B Home

# Include external resources
resources:
  #- url: /local/lovelace/repo-ciotlosm/gauge-card/gauge-card/?v=1
    #type: js
  - url: /local/lovelace/repo-bramkragten/swipe-card/swipe-card.js?v=1
    type: js
  - url: /local/lovelace/button-card/button-card.js?v=1
    type: js
  - url: /local/lovelace/card-modder/card-modder.js?v=1
    type: js
  - url: /local/lovelace/card-tools/card-tools.js?v=1
    type: js
  - url: /local/lovelace/fold-entity-row/fold-entity-row.js?v=1
    type: js
  - url: /local/lovelace/vertical-stack-in-card/vertical-stack-in-card.js?v=1
    type: js

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Each view can have a different theme applied. Theme should be defined in the frontend.
theme: dark-mode
## Exclude entities from "Unused entities" view
#excluded_entities:
  #- weblink.router

views:
  - title: Main
    badges: []
    icon: 'mdi:home'
    cards:


      - type: weather-forecast
        name: Meteorologia
        entity: weather.meteorologia

      - type: glance
        title: Pessoas
        show_state: true
        entities:
          - entity: binary_sensor.notify_home
            name: Casa Ocupada
          - entity: input_boolean.house_guest
            tap_action:
              action: toggle
          - entity: sensor.bianca_status
            name: Bianca
            #icon: mdi:human-female
          - entity: sensor.joao_status
            name: João
            #icon: mdi:human-male



      - type: glance
        title: Luzes/Acções
        show_name: true
        show_state: false
        entities:
          - entity: light.hallwaylight
            name: Luz do Corredor
            tap_action:
              action: toggle
          - entity: switch.flux_sala
            name: Flux Sala
          - entity: input_boolean.night_time
            name: Noite / Sair
            tap_action:
              action: toggle

      - type: thermostat
        name: Aquecimento
        entity: climate.heating

      - type: custom:vertical-stack-in-card
        title: Sala de Estar
        cards:
          - type: media-control
            entity: media_player.media_center
          - type: glance
            title: Luzes
            entities:
              - entity: light.living_room_table
                name: Mesa
                tap_action:
                  action: toggle
              - entity: light.living_room_window
                name: Sofá
                tap_action:
                  action: toggle
              - entity: light.living_room_rgb
                name: Abajur
                tap_action:
                  action: toggle
              - entity: light.tv_leds
                name: TV LEDs
                tap_action:
                  action: toggle
          - type: sensor
            entity: sensor.living_room_temp
            name: Temperatura
            line_color: '#36A2EB'
            line_width: 8
            graph: line

      - type: custom:swipe-card
        parameters:
          spaceBetween: 8
          scrollbar:
            hide: false
            draggable: true
            snapOnRelease: true
        cards:
          - type: sensor
            entity: sensor.tegra_cpu_temperature
            name: Tegra
            line_width: 8
            line_color: '#FF6384'
            graph: line
          - type: sensor
            entity: sensor.helium_cpu_temperature
            name: Helium
            line_color: '#36A2EB'
            line_width: 8
            graph: line



  - title: Configuration
    badges: []
    icon: 'mdi:server'
    cards:
      - entities:
          - entity: input_boolean.notify_home
          - entity: group.all_automations
          - entity: group.all_lights
          - entity: group.all_switches
        type: glance
      - entities:
          - entity: switch.transmission_server
          - entity: sensor.transmission_server_status
          - entity: sensor.transmission_server_active_torrents
          - entity: sensor.transmission_server_down_speed
          - entity: sensor.transmission_server_up_speed
        title: Transmission Status
        type: glance
      - type: history-graph
        entities:
          - sensor.tegra_cpu_temperature
          - sensor.helium_cpu_temperature



