- platform: template
  sensors:
    joao_home:
      value_template: >-
        {{ is_state('group.joao', 'home') }}
    bianca_home:
      value_template: >-
        {{ is_state('group.bianca', 'home') }}
