#!/bin/bash

# RSYNC_FOLDER_REMOTE_HOME
# RSYNC_FOLDER_SERVER
# RSYNC_FOLDER_REMOTE_FOLDER
# RSYNC_EXTRA_OPTS

EXCLUDE_FILE=.rsync_folder_exclude
SYNC_CONF_FILE=.rsync_folder_conf

run_echo()
{
  echo $@
  eval $@
}

# Define inital variables

local_home=$HOME
remote_home=
server=
remote_folder=
extra_opts=

if [[ -f ${SYNC_CONF_FILE} ]]
then
  source ${SYNC_CONF_FILE}
  remote_home=${RSYNC_FOLDER_REMOTE_HOME}
  server=${RSYNC_FOLDER_SERVER}
  remote_folder=${RSYNC_FOLDER_REMOTE_FOLDER}
  extra_opts=${RSYNC_EXTRA_OPTS}
else
  echo "Could not find configuration file ${SYNC_CONF_FILE}"
  exit 1
fi

operation=
args=

# Use > 1 to consume two arguments per pass in the loop (e.g. each
# argument has a corresponding value to go with it).
# Use > 0 to consume one or more arguments per pass in the loop (e.g.
# some arguments don't have a corresponding value to go with it such
# as in the --default example).
for i in "$@"
do
case $i in
  push|pull)
    operation=$i
    ;;
  --delete)
    args="${args} --delete-excluded"
    ;;
  --host=*)
    server="${i#*=}"
    ;;
  --remote-home=*)
    remote_home="${i#*=}"
    ;;
  *)
    echo "unknow option $i"
  ;;
esac
shift # past argument or value
done


rsync_exclude=
if [[ -f ${EXCLUDE_FILE} ]]
then
  rsync_exclude=--exclude-from=${EXCLUDE_FILE}
fi

command=$1

if [[ ! -z $remote_folder ]]
then
  curr_dir="."
  remote_dir="${remote_folder}/"
else
  curr_dir="$( pwd )/"
  remote_dir="$( echo ${curr_dir} | sed "s#${local_home}#${remote_home}#g" )/"
fi


case ${operation} in
    push)
      origin="${curr_dir}"
      destination="${server}:${remote_dir}"
      ;;
    pull)
      origin="${server}:${remote_dir}"
      destination="${curr_dir}"
      ;;
    *)
      exit
      ;;
esac

run_echo "rsync -avzru ${args} ${extra_opts} ${rsync_exclude} ${origin} ${destination}"


